site_name: Test stie
site_url: https://tonyjurg.github.io/testpdoc/
repo_name: 'TF book'
repo_url: https://github.com/tonyjurg/testpdoc

theme: windmill

markdown_extensions:
  - toc:
      permalink: True

extra:
  logo: img/logo.png

nav:
  - Home: index.md
  - About: about.md

